import { chromium } from '@playwright/test';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1 });
const S = async (n) => { await p.waitForTimeout(650); await p.screenshot({ path: `/tmp/sh/m-${n}.png` }) };
await p.goto('http://127.0.0.1:5173/#/app'); await S('01-empty');
await p.getByRole('link', { name: '산책 카드 만들기' }).click(); await S('02-name');
await p.getByLabel('이름').fill('뽀리'); await p.getByRole('button', { name: '다음' }).click(); await S('03-comfort');
await p.getByRole('button', { name: '다음' }).click(); await S('04-greet');
await p.getByRole('button', { name: '다음' }).click(); await p.getByRole('checkbox', { name: '자전거·킥보드' }).check(); await p.getByRole('checkbox', { name: '저녁' }).check(); await S('05-care');
await p.getByRole('button', { name: '카드 미리보기' }).click(); await S('06-done');
await p.getByRole('button', { name: '카드 저장하기' }).click(); await S('07-home');
await p.getByRole('link', { name: /보여주기/ }).click(); await S('08-show');
await p.getByRole('button', { name: '닫기' }).click();
await p.getByRole('link', { name: '산책', exact: true }).click(); await p.getByRole('button', { name: '산책 시작' }).click(); await p.getByRole('button', { name: '마주침 기록' }).click(); await S('09-log');
await p.getByRole('radio', { name: '5m', exact: true }).check(); await p.getByRole('radio', { name: '편안했어요' }).check(); await p.getByRole('button', { name: '기록하기' }).click(); await S('10-walk');
await p.getByRole('button', { name: '산책 끝내기' }).click(); await S('11-summary');
await p.getByRole('link', { name: '나란히', exact: true }).click(); await S('12-ask');
await p.getByRole('button', { name: '동네 직접 고르기' }).click(); await p.getByRole('listitem').filter({ hasText: '망원동' }).click(); await p.waitForTimeout(200); await S('13-loading'); await p.waitForTimeout(900); await S('14-list');
await p.locator('.ncard').filter({ hasText: '두부' }).click(); await S('15-detail');
await p.getByRole('button', { name: '나란히 산책 요청하기' }).click(); await p.getByRole('radio', { name: '저녁' }).check(); await S('16-request');
await p.getByRole('button', { name: '요청 보내기' }).click(); await S('17-pending');
await p.getByRole('button', { name: '나란히 산책 시작' }).click({ timeout: 6000 }); await S('18-intro');
await p.getByRole('button', { name: /에서 걷기 시작/ }).click(); await S('19-walking');
await p.getByRole('button', { name: '지금 확인' }).click(); await S('20-check');
await p.getByRole('button', { name: /둘 다 편안했어요/ }).click(); await p.getByRole('button', { name: '지금 확인' }).click(); await p.getByRole('button', { name: '한쪽이 긴장했어요' }).click(); await S('21-tense');
await p.getByRole('button', { name: /로 물러나 다시 걷기/ }).click(); await p.getByRole('button', { name: '지금 확인' }).click(); await p.getByRole('button', { name: /둘 다 편안했어요/ }).click();
await p.getByRole('button', { name: '지금 확인' }).click(); await p.getByRole('button', { name: /둘 다 편안했어요/ }).click();
await p.getByRole('button', { name: '지금 확인' }).click(); await p.getByRole('button', { name: /둘 다 편안했어요/ }).click();
await p.waitForTimeout(300); if (await p.getByRole('button', { name: '지금 확인' }).count()) { await p.getByRole('button', { name: '지금 확인' }).click(); await p.getByRole('button', { name: /둘 다 편안했어요/ }).click(); }
await S('22-greet');
if (await p.getByRole('button', { name: '짧게 인사했어요' }).count()) await p.getByRole('button', { name: '짧게 인사했어요' }).click();
await S('23-done');
await p.getByRole('link', { name: '사이 기록 보기' }).click(); await S('24-bond');
await b.close();
